package pdc.admin;

/**
 * Created by sebastian on 5/25/17.
 */
public enum AdminResponses {
    HELP,
    LOG_REQUEST,
    ERROR_USERNAME,
    KNOWN_USERNAME,
    ERROR_PASSWORD,
    CONNECTED,
    LOG_OUT,
    ADD_USER,
    USER_IN_USE,
    NEW_USER_OK,
    USER_CREATED,
    BLACK_LIST,
    HOST_BLOCKED,
    PORT_BLOCKED,
    LEET_ON,
    LEET_OFF,
    FLIP_ON,
    FLIP_OFF,
    ALL_METRICS,
    BYTES_SENT,
    BYTES_RECEIVED,
    HISTOGRAMS,
    CONVERTED_CHARS,
    FLIPPED_IMAGES,
    TOTAL_ACCESSES,
    UNAUTHORIZED,
    INTERNAL_ERROR,
    ERROR_BAD_REQUEST
}
